name: "TFC Workspace Name Action"
description: "GitHub Action to generate normalized TFC workspace names"
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  type:
    description: "The type of TFC workspace name. Valid values: feature, repo."
    required: true
  featureBranchName:
    description: "The name of the feature branch from which to derive a feature TFC workspace name."
    required: false
  repoName:
    description: "The name of the repo from which to derive a repo TFC workspace name."
    required: false
  suffix:
    description: "The suffix to append to a repo TFC workspace name."
    required: false
outputs:
  workspaceName:
    description: "The name of the derived TFC workspace."
