name: Release

on:
  push:
    branches:
      - v*.x

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/auto-cancel-redundant-workflow@v1
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run all
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@ed6729b716d281c2c4058d3553f3229a80203a79
        with:
          semantic_version: 17.4.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
